### ISSUE TITLE
How to put *.ts file to a subfolder in the project of an flutter app

### ISSUE THREAD

**Issue by weinixuehao** [hydro-sdk/hydro-sdk#150]
If using the command `node node_modules/hydro-sdk/dist/compiler -t ota/hello_world.ts -m hello-world -d assets -p debug -w ota/hello_world.ts` to build the bytecode does not work as expected with the following error

```
flutter: I/Hydro 0 native, 539 virtual prototypes
flutter: attempt to call a nil value null with []
Error raised in:
  require
     defined in main_chunk:0
VM stacktrace follows:
@.hydroc/9b6821e66ed0d97904619f797a8998096ef8fc0a4375a70febf36d543afb3cff/hello-world:4
  (_Lmain_chunk::d71c39187689639986b4a58c858b8f43c02ed5546a801bc21b68dbaea44632b1::require::file::0)
@.hydroc/9b6821e66ed0d97904619f797a8998096ef8fc0a4375a70febf36d543afb3cff/hello-world:7242
  (null)
Dart stacktrace follows:
#0      Thread.attemptCall
package:hydro_sdk/…/thread/thread.dart:36
#1      tailcall
package:hydro_sdk/…/instructions/tailcall.dart:24
#2      Frame.cont
package:hydro_sdk/…/vm/frame.dart:276
#5      Closure._dispatch
package:hydro_sdk/…/vm/closure.dart:96
#6      Closure.dispatch
package:hydro_sdk/…/vm/closure.dart:83
#7      HydroFunctionImpl.pcall (package:hydro_sdk/hydroState.dart:27:25)<…>

════════ Exception caught by widgets library ═══════════════════════════════════
The following NoSuchMethodError was thrown building RunFromNetwork(dirty, state: _RunFromNetwork#77fd7):
Closure call with mismatched arguments: function 'dispatch'
Receiver: Closure: (List<dynamic>) => Null
Tried calling: dispatch(Instance(length:0) of '_GrowableList', parentState: Instance of 'HydroState')
Found: dispatch(List<dynamic>) => Null

The relevant error-causing widget was
RunFromNetwork
lib/main.dart:11
When the exception was thrown, this was the stack
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      _RunFromNetwork.build
package:hydro_sdk/runFromNetwork.dart:295
#2      StatefulElement.build
package:flutter/…/widgets/framework.dart:4744
#3      ComponentElement.performRebuild
package:flutter/…/widgets/framework.dart:4627
#4      StatefulElement.performRebuild
package:flutter/…/widgets/framework.dart:4800
...
════════════════════════════════════════════════════════════════════════════════
#3      call
package:hydro_sdk/…/instructions/call.dart:22
#4      Frame.cont
package:hydro_sdk/…/vm/frame.dart:271
#5      Closure._dispatch
package:hydro_sdk/…/vm/closure.dart:96
#6      Closure.dispatch
package:hydro_sdk/…/vm/closure.dart:83
#7      HydroFunctionImpl.pcall (package:hydro_sdk/hydroState.dart:27:25)<…>

════════ Exception caught by widgets library ═══════════════════════════════════
Closure call with mismatched arguments: function 'dispatch'
Receiver: Closure: (List<dynamic>) => Null
Tried calling: dispatch(Instance(length:0) of '_GrowableList', parentState: Instance of 'HydroState')
Found: dispatch(List<dynamic>) => Null
The relevant error-causing widget was
RunFromNetwork
```

if put the hello_world.ts into the root dir without an ota folder does working. so the command changed to `node node_modules/hydro-sdk/dist/compiler -t hello_world.ts -m hello-world -d assets -p debug -w ota/hello_world.ts` it OK! why?

**Comment by weinixuehao** [comment]
I suspect `local ____runApp = require("ota.hydro-sdk.runtime.flutter.runApp")` in 7242 line  return null?

**Comment by weinixuehao** [comment]
![image](https://user-images.githubusercontent.com/17869361/101230848-da6cbc00-36e2-11eb-8d95-51278368aeb5.png)
Therefore try to get the closure with the `ota.hydro-sdk.runtime.flutter.runApp` of the HydroTable is NULL.

**Comment by weinixuehao** [comment]
```
--[[ Generated with https://github.com/TypeScriptToLua/TypeScriptToLua ]]
require("lualib_bundle");
local ____exports = {}
local ____runApp = require("ota.hydro-sdk.runtime.flutter.runApp")
local runApp = ____runApp.runApp
local ____index = require("ota.hydro-sdk.runtime.flutter.widgets.index")
local StatelessWidget = ____index.StatelessWidget
local Text = ____index.Text
```
but the preload is the following

```
package.preload["hydro-sdk.runtime.flutter.runApp"] = (function (...)
--[[ Generated with https://github.com/TypeScriptToLua/TypeScriptToLua ]]
local ____exports = {}
function ____exports.runApp(pred)
    hydro.globalBuildResult = pred
end
return ____exports
```
So this is a compiler issue?

**Comment by weinixuehao** [comment]
Finally, Found the location for adding the `rootDir` fixed the issue. 

```
const program = ts.createProgram({
        rootNames: [buildOptions.entry],
        options: {
            strict: true,
            target: ts.ScriptTarget.ES5,
            luaTarget: tstl.LuaTarget.Lua52,
            luaLibImport: tstl.LuaLibImportKind.Require,
            sourceMapTraceback: false,
            outDir: ".hydroc",
            rootDir: "ota",
            include: [
                "node_modules/hydro-sdk/runtime"
            ]
        }
    });
```

```
require("lualib_bundle");
local ____exports = {}
local ____runApp = require("hydro-sdk.runtime.flutter.runApp")
local runApp = ____runApp.runApp
local ____index = require("hydro-sdk.runtime.flutter.widgets.index")
local StatelessWidget = ____index.StatelessWidget

```

The following is a partially compiled Lua code that does not contain `ota,` but this solution is not better as this is hardcoding.
Could add a parameter or a custom tsconfig.json for the compiler since the compiler requires so many parameters`(compiler -t hello_world.ts -m hello-world -d assets -p debug -w hello-world.ts --rootDir?`)

**Comment by weinixuehao** [comment]
#148 
Thanks! the issue has been fixed in the latest version.

**Comment by chgibb** [comment]
Great to hear!

**Comment by weinixuehao** [comment]
```
  anonymous closure
     defined in main_chunk:0
  require
     defined in main_chunk:0
VM stacktrace follows:
@.hydroc/52b02b6df64cc93b73185d1b5f7ca9021cef096a5c1089049f8af71ce20b9ec6/xs_container:4
  (_Lmain_chunk::d71c39187689639986b4a58c858b8f43c02ed5546a801bc21b68dbaea44632b1::require::file::0)
@.hydroc/52b02b6df64cc93b73185d1b5f7ca9021cef096a5c1089049f8af71ce20b9ec6/xs_container:11222
  (_Lmain_chunk::85da869e92f665045ee6ed11917c97bc0ff230010a3958fde05c75686e4bc40e::anonymous_closure::...::0)
@.hydroc/52b02b6df64cc93b73185d1b5f7ca9021cef096a5c1089049f8af71ce20b9ec6/xs_container:4
  (_Lmain_chunk::d71c39187689639986b4a58c858b8f43c02ed5546a801bc21b68dbaea44632b1::require::file::0)
@.hydroc/52b02b6df64cc93b73185d1b5f7ca9021cef096a5c1089049f8af71ce20b9ec6/xs_container:12764
  (null)
Dart stacktrace follows:
Restarted application in 1,920ms.
flutter: I/Hydro 0 native, 563 virtual prototypes
flutter: attempt to call a nil value null with []
Error raised in:
  require
     defined in main_chunk:0
#0      Thread.attemptCall
package:hydro_sdk/…/thread/thread.dart:41
#1    <…>

════════ Exception caught by widgets library ═══════════════════════════════════
The following NoSuchMethodError was thrown building RunFromNetwork(dirty, state: _RunFromNetwork#6dab9):
Closure call with mismatched arguments: function 'dispatch'
Receiver: Closure: (List<dynamic>) => Null
Tried calling: dispatch(Instance(length:0) of '_GrowableList', parentState: Instance of 'HydroState')
Found: dispatch(List<dynamic>) => Null

The relevant error-causing widget was
RunFromNetwork
lib/main.dart:6
When the exception was thrown, this was the stack
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      _RunFromNetwork.build
package:hydro_sdk/runFromNetwork.dart:297
#2      StatefulElement.build
package:flutter/…/widgets/framework.dart:4744
#3      ComponentElement.performRebuild
package:flutter/…/widgets/framework.dart:4627
#4      StatefulElement.performRebuild
package:flutter/…/widgets/framework.dart:4800
...

```
This issue still seems to be exist


[52b02b6df64cc93b73185d1b5f7ca9021cef096a5c1089049f8af71ce20b9ec6.zip](https://github.com/hydro-sdk/hydro-sdk/files/5651353/52b02b6df64cc93b73185d1b5f7ca9021cef096a5c1089049f8af71ce20b9ec6.zip)
@chgibb

**Comment by weinixuehao** [comment]
@chgibb 
I still meet the problem in a case where I made an SDK by meself which depends on the hydro-sdk, I am sorry for reopening this issue.
depend order: app -> mysdk -> hydro-sdk
Can only find `package.preload["src.@hydro-sdk.hydro-sdk.runtime.flutter.widgets.index"] = (function (...)` in the .hydroc
so this `local ____index = require("src.mysdk.libts.widgets.@hydro-sdk.hydro-sdk.runtime.flutter.widgets.index")` return null.

**Comment by chgibb** [comment]
I don't think your use case of making an SDK between Hydro and your app is something we should be supporting this early.

**Comment by weinixuehao** [comment]
@chgibb 
As I have some custom widgets and hook function to add for sharing on multiple app, It is impossible to rewrite this code for each app? or you have an idea if you have no plan to support now.

**Comment by chgibb** [comment]
The intent is to eventually provide a registry similar to Definitely Typed that will hold automatically generated bindings for packages on `pub.dev` with consumers making use of `waveform` to install and manage them.

**Comment by weinixuehao** [comment]
@chgibb Do you have a temp solution?

**Comment by chgibb** [comment]
Allowing the user to specify their own tsconfig would be possible. Would you mind describing what fields from tsconfig you need to customize in a separate issue please?

**Comment by weinixuehao** [comment]
@chgibb 
OK!
