### ISSUE TITLE
Question about examples

### ISSUE THREAD

**Issue by fatkullinalina** [hydro-sdk/hydro-sdk#162]
Hi
What command do ypu use to compile for example  to unityGallery.hc?
When i use files from dist folder everything is ok, but when i try to compile and then run these files, it doesn't work

**Comment by fatkullinalina** [comment]
I/flutter (31050): I/Hydro 0 native, 568 virtual prototypes
I/flutter (31050): Null check operator used on a null value
I/flutter (31050): VM stacktrace follows:
I/flutter (31050): null:null
I/flutter (31050):   (null)
I/flutter (31050): null:null
I/flutter (31050):   (null)
I/flutter (31050): Dart stacktrace follows:
I/flutter (31050): #0      Navigator.push (package:flutter/src/widgets/navigator.dart:2095)
I/flutter (31050): #1      loadNavigator.<anonymous closure> (package:hydro_sdk/cfr/builtins/libs/flutter/widgets/navigator.dart:12)
I/flutter (31050): #2      Thread.attemptCall (package:hydro_sdk/cfr/thread/thread.dart:35)
I/flutter (31050): #3      call (package:hydro_sdk/cfr/vm/instructions/call.dart:27)
I/flutter (31050): #4      Frame.cont (package:hydro_sdk/cfr/vm/frame.dart:271)
I/flutter (31050): #5      call (package:hydro_sdk/cfr/vm/instructions/call.dart:22)
I/flutter (31050): #6      Frame.cont (package:hydro_sdk/cfr/vm/frame.dart:271)
I/flutter (31050): #7      Closure._dispatch (package:hydro_sdk/cfr/vm/closure.dart:96)
I/flutter (31050): #8      Closure.dispatch (package:hydro_sdk/cfr/vm/closure.dart:83)
I/flutter (31050): #9      loadGestureDetector.<anonymous closure>.<anonymous closure> (package:hydro_sdk/cfr/builtins/libs/flutter/widgets/gestureDetector.dart:19)
I/flutter (31050): #10     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:183)
I/flutter (31050): #11     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:598)
I/flutter (31050): #12     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:302)
I/flutter (31050): #13     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:222)
I/flutter (31050): #14     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:476)
I/flutter (31050): #15     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:77)
I/flutter (31050): #16     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:122)
I/flutter (31050): #17     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377)
I/flutter (31050): #18     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:120)
I/flutter (31050): #19     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:106)
I/flutter (31050): #20     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:381)
I/flutter (31050): #21     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:361)
I/flutter (31050): #22     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:279)
I/flutter (31050): #23     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:316)
I/flutter (31050): #24     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:280)
I/flutter (31050): #25     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:238)
I/flutter (31050): #26     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:221)
I/flutter (31050): #27     _rootRunUnary (dart:async/zone.dart:1206)
I/flutter (31050): #28     _CustomZone.runUnary (dart:async/zone.dart:1100)
I/flutter (31050): #29     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005)
I/flutter (31050): #30     _invoke1 (dart:ui/hooks.dart:176)
I/flutter (31050): #31     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:276)
I/flutter (31050): #32     _dispatchPointerDataPacket (dart:ui/hooks.dart:96)
I/flutter (31050):
I/flutter (31050): #0      Closure.dispatch (package:hydro_sdk/cfr/vm/closure.dart:86)
I/flutter (31050): #1      loadGestureDetector.<anonymous closure>.<anonymous closure> (package:hydro_sdk/cfr/builtins/libs/flutter/widgets/gestureDetector.dart:19)
I/flutter (31050): #2      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:183)
I/flutter (31050): #3      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:598)
I/flutter (31050): #4      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:302)
I/flutter (31050): #5      BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:222)
I/flutter (31050): #6      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:476)
I/flutter (31050): #7      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:77)
I/flutter (31050): #8      PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:122)
I/flutter (31050): #9      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377)
I/flutter (31050): #10     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:120)
I/flutter (31050): #11     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:106)
I/flutter (31050): #12     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:381)
I/flutter (31050): #13     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:361)
I/flutter (31050): #14     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:279)
I/flutter (31050): #15     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:316)
I/flutter (31050): #16     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:280)
I/flutter (31050): #17     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:238)
I/flutter (31050): #18     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:221)
I/flutter (31050): #22     _invoke1 (dart:ui/hooks.dart:176)
I/flutter (31050): #23     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:276)
I/flutter (31050): #24     _dispatchPointerDataPacket (dart:ui/hooks.dart:96)
I/flutter (31050): (elided 3 frames from dart:async)



also I han=ve some troubles with navigator.push, but again if i use your .hc code everything is ok

**Comment by chgibb** [comment]
`unityGallery` is built by `scripts/buildAllTs.bash` during CI. What command are you using to build it that results in a broken file?
