### ISSUE TITLE
Execute npm run test:compiler failed on the master branch

### ISSUE THREAD

**Issue by lyxia** [hydro-sdk/hydro-sdk#322]
npm run test:compiler
(node:49408) ExperimentalWarning: The fs.promises API is experimental

> @hydro-sdk/hydro-sdk@0.0.1 test:compiler
> npm run build:compiler && bash scripts/jest.bash

(node:49415) ExperimentalWarning: The fs.promises API is experimental

> @hydro-sdk/hydro-sdk@0.0.1 build:compiler
> bash scripts/buildCompiler.bash

ts-jest[config] (WARN) message TS151001: If you have issues related to imports, you should consider setting `esModuleInterop` to `true` in your TypeScript configuration file (usually `tsconfig.json`). See https://blogs.msdn.microsoft.com/typescript/2018/01/31/announcing-typescript-2-7/#easier-ecmascript-module-interoperability for more information.
ts-jest[config] (WARN) message TS151001: If you have issues related to imports, you should consider setting `esModuleInterop` to `true` in your TypeScript configuration file (usually `tsconfig.json`). See https://blogs.msdn.microsoft.com/typescript/2018/01/31/announcing-typescript-2-7/#easier-ecmascript-module-interoperability for more information.
ts-jest[config] (WARN) message TS151001: If you have issues related to imports, you should consider setting `esModuleInterop` to `true` in your TypeScript configuration file (usually `tsconfig.json`). See https://blogs.msdn.microsoft.com/typescript/2018/01/31/announcing-typescript-2-7/#easier-ecmascript-module-interoperability for more information.
 FAIL  test/compiler/fullyQualifiedFunctionName.test.ts
  ● 

    TypeError: utils_1.castArray(...).flatMap is not a function

      at TransformationContext.transformStatements (node_modules/typescript-to-lua/dist/transformation/context/context.js:71:40)
      at Object.exports.transformSourceFileNode [as transform] (node_modules/typescript-to-lua/dist/transformation/visitors/sourceFile.js:27:63)
      at TransformationContext.transformNode (node_modules/typescript-to-lua/dist/transformation/context/context.js:45:62)
      at Object.transformSourceFile (node_modules/typescript-to-lua/dist/transformation/index.js:29:30)
      at processSourceFile (node_modules/typescript-to-lua/dist/transpilation/transpile.js:52:96)
      at sourceFile (node_modules/typescript-to-lua/dist/transpilation/transformers.js:22:9)
      at transformSourceFileOrBundle (node_modules/typescript-to-lua/node_modules/typescript/lib/typescript.js:76524:57)
      at transformation (node_modules/typescript-to-lua/node_modules/typescript/lib/typescript.js:94097:24)
      at transformRoot (node_modules/typescript-to-lua/node_modules/typescript/lib/typescript.js:94118:82)
      at Object.map (node_modules/typescript-to-lua/node_modules/typescript/lib/typescript.js:551:29)

 FAIL  test/compiler/moduleDebugInfo.test.ts (5.865 s)
  ● 

    TypeError: utils_1.castArray(...).flatMap is not a function

      at TransformationContext.transformStatements (node_modules/typescript-to-lua/dist/transformation/context/context.js:71:40)
      at Object.exports.transformSourceFileNode [as transform] (node_modules/typescript-to-lua/dist/transformation/visitors/sourceFile.js:27:63)
      at TransformationContext.transformNode (node_modules/typescript-to-lua/dist/transformation/context/context.js:45:62)
      at Object.transformSourceFile (node_modules/typescript-to-lua/dist/transformation/index.js:29:30)
      at processSourceFile (node_modules/typescript-to-lua/dist/transpilation/transpile.js:52:96)
      at sourceFile (node_modules/typescript-to-lua/dist/transpilation/transformers.js:22:9)
      at transformSourceFileOrBundle (node_modules/typescript-to-lua/node_modules/typescript/lib/typescript.js:76524:57)
      at transformation (node_modules/typescript-to-lua/node_modules/typescript/lib/typescript.js:94097:24)
      at transformRoot (node_modules/typescript-to-lua/node_modules/typescript/lib/typescript.js:94118:82)
      at Object.map (node_modules/typescript-to-lua/node_modules/typescript/lib/typescript.js:551:29)

  ● 

    TypeError: utils_1.castArray(...).flatMap is not a function

      at TransformationContext.transformStatements (node_modules/typescript-to-lua/dist/transformation/context/context.js:71:40)
      at Object.exports.transformSourceFileNode [as transform] (node_modules/typescript-to-lua/dist/transformation/visitors/sourceFile.js:27:63)
      at TransformationContext.transformNode (node_modules/typescript-to-lua/dist/transformation/context/context.js:45:62)
      at Object.transformSourceFile (node_modules/typescript-to-lua/dist/transformation/index.js:29:30)
      at processSourceFile (node_modules/typescript-to-lua/dist/transpilation/transpile.js:52:96)
      at sourceFile (node_modules/typescript-to-lua/dist/transpilation/transformers.js:22:9)
      at transformSourceFileOrBundle (node_modules/typescript-to-lua/node_modules/typescript/lib/typescript.js:76524:57)
      at transformation (node_modules/typescript-to-lua/node_modules/typescript/lib/typescript.js:94097:24)
      at transformRoot (node_modules/typescript-to-lua/node_modules/typescript/lib/typescript.js:94118:82)
      at Object.map (node_modules/typescript-to-lua/node_modules/typescript/lib/typescript.js:551:29)

  ● 

    TypeError: utils_1.castArray(...).flatMap is not a function

      at TransformationContext.transformStatements (node_modules/typescript-to-lua/dist/transformation/context/context.js:71:40)
      at Object.exports.transformSourceFileNode [as transform] (node_modules/typescript-to-lua/dist/transformation/visitors/sourceFile.js:27:63)
      at TransformationContext.transformNode (node_modules/typescript-to-lua/dist/transformation/context/context.js:45:62)
      at Object.transformSourceFile (node_modules/typescript-to-lua/dist/transformation/index.js:29:30)
      at processSourceFile (node_modules/typescript-to-lua/dist/transpilation/transpile.js:52:96)
      at sourceFile (node_modules/typescript-to-lua/dist/transpilation/transformers.js:22:9)
      at transformSourceFileOrBundle (node_modules/typescript-to-lua/node_modules/typescript/lib/typescript.js:76524:57)
      at transformation (node_modules/typescript-to-lua/node_modules/typescript/lib/typescript.js:94097:24)
      at transformRoot (node_modules/typescript-to-lua/node_modules/typescript/lib/typescript.js:94118:82)
      at Object.map (node_modules/typescript-to-lua/node_modules/typescript/lib/typescript.js:551:29)

 FAIL  test/compiler/bundleWithDebugInformation.test.ts (8.749 s)
  ● 

    TypeError: utils_1.castArray(...).flatMap is not a function

      at TransformationContext.transformStatements (node_modules/typescript-to-lua/dist/transformation/context/context.js:71:40)
      at Object.exports.transformSourceFileNode [as transform] (node_modules/typescript-to-lua/dist/transformation/visitors/sourceFile.js:27:63)
      at TransformationContext.transformNode (node_modules/typescript-to-lua/dist/transformation/context/context.js:45:62)
      at Object.transformSourceFile (node_modules/typescript-to-lua/dist/transformation/index.js:29:30)
      at processSourceFile (node_modules/typescript-to-lua/dist/transpilation/transpile.js:52:96)
      at sourceFile (node_modules/typescript-to-lua/dist/transpilation/transformers.js:22:9)
      at transformSourceFileOrBundle (node_modules/typescript/lib/typescript.js:74631:57)
      at transformation (node_modules/typescript/lib/typescript.js:92009:24)
      at transformRoot (node_modules/typescript/lib/typescript.js:92030:82)
      at Object.map (node_modules/typescript/lib/typescript.js:551:29)

Test Suites: 3 failed, 3 total
Tests:       5 failed, 5 total
Snapshots:   0 total
Time:        9.225 s
Ran all test suites.

**Comment by chgibb** [comment]
Hi @lyxia , thanks for trying out Hydro!

What version of Node and what operating system are you on?

**Comment by lyxia** [comment]
operating system: macOS Catalina 10.15.7
node version: v10.16.3

**Comment by chgibb** [comment]
CI currently runs compiler tests on Node 14.15.5 and Mac OS 10.14. I would recommend using a version of Node at least as high.

**Comment by lyxia** [comment]
Test passed, Thank you~
